version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8888:80
    depends_on:
      - app
    container_name: nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - node
    container_name: app

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: stories
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 7777:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql

  node:
    image: node:alpine
    volumes:
      - ./:/var/www
    ports:
      - 5173:5173
    working_dir: /var/www
    command: [
        "yarn", "run", "dev",
        "--port", "${VITE_PORT:-5173}",
        "--host", "0.0.0.0"
    ]
    container_name: node
